### ISSUE TITLE
Quaternion to Euler Angle issue

### ISSUE THREAD

**Issue by DrBeef** [DrBeef/QuakeQuest#11]
Orientation when headset looking near poles (north or south) doesn't work very well at all (Quaternion to Euler Angle issue). 

If anyone knows what's going on there I'd appreciate some help!, it was like this on the GearVR.

This could really do with fixing, but I've not been able to and it needs someone else to take a look.

**Comment by baggyg** [comment]
Dr Beef has fixed this in latest commit!
