### ISSUE TITLE
[Solution] Simplified build process with (almost) no environment prerequisites.

### ISSUE THREAD

**Issue by BrainSlugs83** [DrBeef/QuakeQuest#15]
I had a helluva time getting this project (or any of the OVR samples) to build on Windows... and each machine I tried to build on ran into different issues -- I eventually got it working in several environments (and your comments in the `readme.md`, about what to install, were super helpful, even if they didn't give a ton of guidance, it gave me a place to start digging. -- Android is not my native development stack, so I was *very* lost for quite a while, but the digging paid off! 💪).

So, to get around ever having to do that again (and hopefully to save others the same trouble!), I've created a simple docker image that anyone can use to build QuakeQuest (or similar native projects built from the templates present in the OVR SDK, version 1.23).

This process does not have any prerequisites (except for having docker installed and being logged in to it with a free docker hub account). 

To download the image, (you only need to do this once) just run:
```
docker pull brainslugs83/ovrsdk
```

Then to compile any project, just go into that directory and run `docker run -it --rm -v %cd%:/proj brainslugs83/ovrsdk /opt/build.sh`, e.g.:

```
:: Clone the QuakeQuest Repo
git clone https://github.com/DrBeef/QuakeQuest.git
cd QuakeQuest

:: Kick off a Build
docker run -it --rm -v %cd%:/proj brainslugs83/ovrsdk /opt/build.sh

:: Verify the build output
dir *.apk 
```

The current github repo for this project is located at: https://github.com/BrainSlugs83/DockerOvrSdk

Feel free to share these steps around, or to suggest improvements -- I really hope this helps someone! 🙂

**Comment by DrBeef** [comment]
That's amazing work!, thank-you for doing this, hopefully it'll encourage others to consider seeing what else they could do with the native samples or even making some pull requests for enhancements to QuakeQuest (or the next project.....).

I'll add a link to your repo from the readme so people are aware of it!

**Comment by BrainSlugs83** [comment]
Thanks, glad to help!
