### ISSUE TITLE
Unable to start game on latest Oculus firmware

### ISSUE THREAD

**Issue by megaRammy** [DrBeef/QuakeQuest#16]
Installing the latest version with the new Oculus update **(Headset version 333700.2680.0)**, I cannot get past the main menu. I believe this is due to the new update having some Oculus Go emulation inside, meaning that sideloaded APKs without the [right string in the manifest](https://www.reddit.com/r/OculusQuest/comments/chjpu5/fix_for_sideloadedhomebrew_apps_and_games_with/) to specify it's a Quest game will run in Go mode, with a single 3DOF controller etc.

### Potential fix

[Using this fix](https://www.reddit.com/r/OculusQuest/comments/chjpu5/fix_for_sideloadedhomebrew_apps_and_games_with/) and [signing/zipaligning](https://www.reddit.com/r/OculusQuest/comments/chselu/batch_file_to_fix_apk_for_sideloading/euzj73x/?utm_source=share&utm_medium=web2x) the APK after, allows me to play the game once more. I have manually added the string to the Android Manifest file, I do not have a setup to compile the APK manually currently so this should be tested before release

**Comment by baggyg** [comment]
Unfortunately I don't have the latest update as yet. As soon as I have that I can test an official fix.

**Comment by megaRammy** [comment]
If you can compile it, I can quickly test if the startup issue occurs on my Quest no worries! But if you have a larger test setup/plan you want to run, then fair, godspeed on the update :P

**Comment by baggyg** [comment]
It doesn't compile with that line due the the Oculus SDK version we are using. I need to have a proper look over the weekend. If we upgrade SDK we need to work in app privileges. Hence why it will be much quicker if I have the update to test it. 

Thanks for the offer though. I am sure we will have a fix soon :-)

**Comment by megaRammy** [comment]
Fair enough, got the feeling it might be more complex to fix properly :P hopefully the update pushes soon, and thanks for all the amazing work!

**Comment by Jervi71** [comment]
Hi,
I have decompiled apk, added the line in manifest and recompiled. The game starts and controls are ok, but has problems after a while. 
If I look in a particular direction, the screen goes black. It never gave me this problem with the Quest's previous firmware.
I hope you resolve. Quake in my opinion is one of the best game for Quest!
Thanks

**Comment by Jervi71** [comment]
Hi,
with the last update Quake works. Thanks! Sometimes when I come back to the main game menu, I don't see it. I can interact with the controls but the screen is black.

It also happened that by quitting the game using 'Quiet game' from the main menu, the application crashes.

Strangely in the main menu the version displayed is 1.2.1

**Comment by slydog43** [comment]
I have seen the black screen also when I try to load/save after hitting the menu button.  The display is there, but it seems to be displayed way off (ie I have to look up or down or from side to side to find it).  Not always but a fair amount.  thanks for such an awesome port.

**Comment by baggyg** [comment]
The core issue here is fixed. Please report separate issues in their own thread.
