### ISSUE TITLE
App crash when quit

### ISSUE THREAD

**Issue by Jervi71** [DrBeef/QuakeQuest#18]
Hi,
with new Quest firmware it happened that exiting the game using 'Quiet' from the main menu, the application crashes with a message.

**Comment by slydog43** [comment]
I also experience this, so its not an isolated issue.  Although I think DrBeef is busy today with other releases :)

**Comment by DrBeef** [comment]
Indeed!, though you'll get the same thing on Lambda1VR too until I figure
out what I did to introduce this (and how to fix it)

**Comment by DrBeef** [comment]
Closing as I'm unlikely to try to fix this (if I'm being honest)
