### ISSUE TITLE
Cant Launch Quake Quest

### ISSUE THREAD

**Issue by vrjunkie** [DrBeef/QuakeQuest#19]
Hi,

I am having trouble playing Quake Quest.

I loaded SideQuest and used it to load QuakeQuest - I ran it and it was AWESOME - ONCE!
I cannot get back into the game. Whenever I go to Unapproved sources and launch it - all I get is the intro movie - There is no menu!

Pressing either trigger does nothing,  A or X does nothing, the side/grip buttons does nothing, the menu button does nothing,  the sticks do nothing, the Oculus button takes me to home where I can resume or exit, and the B and Y buttons take me to the home screen where there is not an option to resume or exit.

I'm guessing the menu button is supposed to bring up the menu but does not - I have looked at ever inch of 360 space and there is nothing or it is black. I have even assumed there is a menu that I cannot see and tried blindly using the sticks to move a possibly unseen menu bar and proceed and it does nothing.

I have restarted my Quest multiple times, as well as using SideQuest to uninstall and reinstall to no avail.

I even used SideQuest to manually remove residual files and folder structures removing any possible problems and then reinstalled to no avail.

Is anyone else having this problem or have a solution - PLEASE advise.  I am a HUGE Quake fan and 1st played it in the late 90's using a VFX1 headset and only dreamed back then of what was possible - 6DOF Quake is phenomanal and I MUST have it back - LOL!

**Comment by baggyg** [comment]
The only time I experienced that is when we were testing the build for the new update. I am wondering whether the sidequest version has an issue. As a sanity check can you download the latest APK from https://github.com/DrBeef/QuakeQuest/releases/tag/V1.2.3 and install (via dragging over sidequest top left corner) and see if that version is the same?

**Comment by vrjunkie** [comment]
This TOTALLY fixed my issue - THANK YOU - THANK YOU - THANK YOU!!!!!

Respectfully,

Lane
