### ISSUE TITLE
About the FOV

### ISSUE THREAD

**Issue by animemoko** [DrBeef/QuakeQuest#2]
FOV is a little reduced, reminds me my Rift Fov now, Quest has little more Fov and I'd like to enjoy it :)

**Comment by DrBeef** [comment]
Latest release should resolve this issue, please see V1.1.0 release notes

**Comment by animemoko** [comment]
That was fast! Thanks very much!

**Comment by neitey** [comment]
seems fixed

**Comment by DrBeef** [comment]
Closing as I also believe it is sorted
