### ISSUE TITLE
Menu button doesn't work

### ISSUE THREAD

**Issue by Salbrox** [DrBeef/QuakeQuest#20]
I cannot start a game because the menu button on left controller does nothing when i press it. The game opens but i'm stuck unable to open the menu to start a game. Is there a fix for this?

**Comment by DrBeef** [comment]
I'm not sure I understand the issue. When the game starts the first thing
you see is the menu, allowing you to start a New Game.

Could you record a short video demonstrating the issue please?

Thanks!

**Comment by Salbrox** [comment]
Thanks for your response.

Ok, so that is not happening on my quest. There is a demo playing in the background and there is a text dialog with the quake quest text. No menu appears. I'll record a video today when I have a few mins.

On Sat 10 Aug 2019, 07:24 Simon, <notifications@github.com<mailto:notifications@github.com>> wrote:
I'm not sure I understand the issue. When the game starts the first thing
you see is the menu, allowing you to start a New Game.

Could you record a short video demonstrating the issue please?

Thanks!

**Comment by Salbrox** [comment]
Hi sorry for delay in getting back to you. This issue was because I downloaded the old version from the link in sidequest. Once I got a more up-to date build it started properly. Its great fun btw. Is there full 6dof head tracking? When I walk in the real world it doesn't seem to move in game.

**Comment by DrBeef** [comment]
Good news it is working now. I just want to check though, you did install
the Quest version and not the Go version?, there should be full 6DoF head
tracking, as well as for the weapon. There is an update coming over the
next day or so, so you will find it an even better experience after that.

**Comment by Salbrox** [comment]
It was this link provided to me by someone on r/OculusQuest:
[https://drive.google.com/file/d/1CaHnsnrkKVwRxH3QwRNPGSENPdoRKupu/view?usp=drivesdk](url)

**Comment by Salbrox** [comment]
It is 
quakequest-1.2.2 zipaligned.apk

**Comment by DrBeef** [comment]
OK, I don't know what that is.. that's not even a link to the release on
github, which is a bit strange!

I would download the latest release on the QuakeQuest github repo and
install that, alternatively, wait a bit (possibly later today if I get
time) and watch out for version 1.4.0 to be released and then install that.

You are playing this on an Oculus Quest aren't you?

**Comment by Salbrox** [comment]
Yep its on quest

**Comment by Salbrox** [comment]
Any APK link or will I have to build with Android studio?

**Comment by baggyg** [comment]
I expect the mentioned apk was the unofficial one people patched when the oculus update broke most sideloaded.

**Comment by DrBeef** [comment]
You can download the apk from this repo. The latest version is now live:

https://github.com/DrBeef/QuakeQuest/releases/tag/v1.4.0

I'm going to close this issue now, please reply if you are still having an issue
