### ISSUE TITLE
Stuck in 3rd Person?

### ISSUE THREAD

**Issue by carbonark** [DrBeef/QuakeQuest#26]
Hello,

For some reason the game is in third person, I'm not sure what happened to make this happen but I can't seem to find any menu item that I could have pressed to cause this. Could you help? I have uninstalled and re-installed several times

**Comment by DrBeef** [comment]
Sounds like you've somehow managed to set the chase_active cvar to 1, if
you see that cvar in you config.cfg just delete it and hopefully it will go
back to first person again!
