### ISSUE TITLE
Still a bit of warping when looking around

### ISSUE THREAD

**Issue by neitey** [DrBeef/QuakeQuest#28]
There is still a bit of warping going on when turning your head. Not much, but a lot of people on reddit claim they can still "sense" it. It is definitely there and observable when the guardian is forced up.

FoV seems right, i think the "vr_positional_factor" is just a bit off. Can't try and error and change the VR values myself because these seemed  to be hard coded now.

**Comment by DrBeef** [comment]
fov was set to 106, I'm adjusting it to 104 to match the other ports, that should sort it.
