### ISSUE TITLE
More death zone to the thumbstick

### ISSUE THREAD

**Issue by neitey** [DrBeef/QuakeQuest#30]
I would like to suggest to  add a death zone to the thumbsticks, because after heavy use my right thumbstick is starting to wear out and its starting to not center 100 % correctly. That is already translated into unintentional movements in the game. As the Quest and the controllers are getting more and more wear and tear, i think a bigger thumbstick deadzone will become necessary in all ports.

**Comment by DrBeef** [comment]
I'm adding the same movement scaler that QuestZDoom uses.. new release coming soon
