### ISSUE TITLE
[Suggestion] Add water transparency, fixed weapons angle and light flicker interpolation to default config.cfg

### ISSUE THREAD

**Issue by neitey** [DrBeef/QuakeQuest#31]
"r_wateralpha" "0.700000"   // makes water transparent and adds to the gameplay.

"cl_weaponpitchadjust" "35"   // gives all weapons a more natural grip angle. seems to be hardcoded now to "-2"

"r_lerplightstyles" "1"   // interpolation for flickering lights, it gives less eye strain and looks nicer.

just small tweaks is stumbled upon. No performance impact.

**Comment by clayg** [comment]
@neitey there's more than one suggestion here :grin: 

Can you clarify *where* you'd suggest these settings would go?  [here](https://github.com/DrBeef/QuakeQuest/blob/master/assets/config.cfg)?

Can you elaborate what you mean by "hardcoded"?  When I browse my id1 folder where I added my pak files via sidequest there's a config.cfg there that I've tried editing.  My cl_weaponpitchadjust was set to "11" (not sure how).

**Comment by DrBeef** [comment]
Fixing in next update 1.4.4

**Comment by seascape** [comment]
May I ask if water transparency works? I have it enabled and believe my very old .pak files are "vis'ed" as we used to say ([tutorial](https://www.quakewiki.net/archives/retroquake.planetquake.gamespy.com/blog/index1e7e.html?p=34)) but all liquids in Quake1Quest remain opaque.
