### ISSUE TITLE
Quest2 / 90Hz mode..

### ISSUE THREAD

**Issue by AmmarkoV** [DrBeef/QuakeQuest#33]
Hello,
Thanks for your great work!
I am happily running Quake however I noticed that the new "unlocked" 90Hz framerate for the Quest 2 is not utilized since framerate is a constant 72Hz.

As read here :
https://developer.oculus.com/blog/-oculus-quest-v23-how-to-update-your-app-for-90hz/

It appears that the 
```
<meta-data android:name="com.oculus.supportedDevices" android:value="quest|delmar"/>
```
has to be added to the manifest ( https://developer.oculus.com/documentation/native/android/mobile-native-manifest/ )
And then it should be automatically used ?

**Comment by baggyg** [comment]
Yes we are aware of this and will hopefully be updating at some point soon.

**Comment by AmmarkoV** [comment]
Thanks again!

**Comment by AmmarkoV** [comment]
Just fyi there is a new version ( v23.0 ) of the [Mobile SDK](https://developer.oculus.com/downloads/package/oculus-mobile-sdk/) and some updated developer rules on setting everything up for 90hz 

https://developer.oculus.com/documentation/native/android/mobile-72hz/

**Comment by AmmarkoV** [comment]
I added the 90Hz mode and made a pull request 
https://github.com/DrBeef/QuakeQuest/pull/34
