### ISSUE TITLE
Install instructions without sidequest

### ISSUE THREAD

**Issue by Kazlehoff** [DrBeef/QuakeQuest#38]
Hey,

Running Win11 which is as of now not compatible with sidequest.

How can i go about manually installing the APK on my quest 2?

**Comment by baggyg** [comment]
There's probably other interfaces out, but better to perhaps go to the core and use adb:
https://developer.android.com/studio/command-line/adb

I also think there is a mobile phone version of sidequest available although not tried it myself.
