### ISSUE TITLE
Smooth turning speed slider disabled in options menu

### ISSUE THREAD

**Issue by BenMcLean** [DrBeef/QuakeQuest#4]
When I try to set the game to "Smooth Turning" mode, the menu has it stuck on the default turning speed. I can see a slider in the menu for turning speed, but pressing down doesn't allow navigating to that menu item to change the speed. Please fix! Thanks

**Comment by ZachDrach** [comment]
Same here.

**Comment by DrBeef** [comment]
Latest release should resolve this issue, please see V1.1.0 release notes
