### ISSUE TITLE
Right stick controls

### ISSUE THREAD

**Issue by psychoblizzard** [DrBeef/QuakeQuest#40]
I find myself accidentally changing weapons while turning left and right quite often. It would be great if there were an option to have the right stick look up and down, same as in console games, while allocating weapon changing to buttons on the left controller or having a weapon wheel. It would make using the right stick feel more intuitive for me. Is there perhaps any way to set that in the console?

**Comment by baggyg** [comment]
Having the pitch linked to joystick is a major no-no for VR. You can possibly look to remap controls using the Oculus tool they released in the latest firmware

**Comment by psychoblizzard** [comment]
Having played a bit more, I've gotten used to playing standing up (instead of on the couch) and just physically turning to face where I want to go, so it's all working great actually. Good to know about the tool for remapping though, thanks. I played through the first three levels today, had a great time, awesome project.

**Comment by baggyg** [comment]
Glad you are enjoying it!
