### ISSUE TITLE
Can't join online match

### ISSUE THREAD

**Issue by animemoko** [DrBeef/QuakeQuest#6]
We still can't type "2" in order to join the game.
The keyboard does work in the console command but this does not allow to "press 2" when asked by the splash window before joining a match.

**Comment by DrBeef** [comment]
Can you let me know which server that is please? I'll have a try at some
point, was hoping I'd fixed it but didn't actually try a server that asked
for input.

**Comment by animemoko** [comment]
"NewDM USA" in Darkplaces server list, now I realise not all serves have that welcome splash screen, I was just trying to join that one since there was people playing, or maybe they are bots I don't know.

**Comment by DrBeef** [comment]
This is definitely fixed in 1.2.1
