### ISSUE TITLE
In 3DoF weapons mode the player rotates not around the center axis.

### ISSUE THREAD

**Issue by neitey** [DrBeef/QuakeQuest#7]
As stated in the "known issues" the  player is the weapon. his position is the weapons position. This causes that when the player turn around it feels a bit off, cause the rotation doesn't completely aligns with the real center axis of the player and it shifts the player around.

If there is no other way to do 6DoF, so be it. In the heat of battle this is hardly noticeable.

But this off axis alignment is also the case in the comfort 3DoF mode. So also here the weapon seems to be the center of rotation not the player. **So there is no comfort benefit between 3DoF and 6DoF**

Maybe there is a way to make it as it was in the 3DoF Gear vr version?

EDIT: i am not so sure anymore what is happening exactly, but something is a bit off in 3DoF.

**Comment by DrBeef** [comment]
Going to close this on the assumption that under the new scheme, everything is better
