### ISSUE TITLE
Virtual Keyboard - "Space" is broken

### ISSUE THREAD

**Issue by neitey** [DrBeef/QuakeQuest#9]
Using the build in on screen keyboard seems not to work right regarding the "SPACE" key.

I tried to run a script. 

`EXEC bot.cfg`

Got the message: Command "EXEC bot.cfg" unknown

Tried EXEC alone and it worked as it should, Tried EXEC with a space at the end and it prompted Command "EXEC   " unknown.

Seems like the SPACE key is behaving like a invisible underscore.

**Comment by DrBeef** [comment]
Can you try this build please?

https://drive.google.com/file/d/1o5eobUAEtaFrTNmwndlmJGBomM_F8A7o/view?usp=sharing

May not fix it, but worth a try..

**Comment by neitey** [comment]
Thanks for the 1.2.2 Beta. I tried it, but sadly did not fix the input issue.

This is i minor problem. But with a fully functioning input system, we could start bot games without using another device as a server. And of course test console commands without a BT keyboard.
